version: '3'

#networks:
#  default:
#    external:
#      name: my_network

services:
  service:
    build: app
    container_name: django
    env_file:
      - app/config/.env
    depends_on:
      - db
#    command: python manage.py collectstatic

  db:
    image: postgres:13
    env_file:
      - app/config/.env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - service
    ports:
      - "81:81"
