version: '3'

#networks:
#  default:
#    external:
#      name: my_network

services:
  service:
    build: app
    container_name: django
    env_file:
      - app/config/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
#    command: python manage.py collectstatic

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=movies_database
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=1234
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - service
    ports:
      - "81:81"
